#!/bin/bash

remote="$1"
url="$2"

valid_branch_regex="^(chore|docs|feat|fix|merge|perf|refact|refactor|style|test|wip)\/[A-Z_]{1,10}-[0-9]{1,10}.*$"
message="Branch names must adhere to this contract: $valid_branch_regex. You should rename your branch to a valid name and try again."
zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid; do
  if test "$local_oid" = "$zero"; then
    # Handle delete
    :
  else
    remote_branch="$(git rev-parse --abbrev-ref $remote_ref)"
    if ! [[ $remote_branch =~ $valid_branch_regex ]]; then
      echo "$message"
      exit 1
    fi

    if test "$remote_oid" = "$zero"; then
      # New branch, examine all commits
      range="$local_oid"
    else
      # Update to existing branch, examine new commits
      range="$remote_oid..$local_oid"
    fi

    # Check for WIP commit
    commit=$(git rev-list -n 1 --grep '^WIP' -i "$range")
    if test -n "$commit"; then
      echo >&2 "Found WIP commit in $local_ref, not pushing"
      exit 1
    fi
  fi
done

exit 0
